apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetris-game
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:jovestefanovski/tetris-game.git
    targetRevision: HEAD
    path: manifests
  destination: 
    server: https://kubernetes.default.svc
    namespace: tetrisgame

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: false
      prune: true